Fix selecting of right TF in TF view.
This commit fixes the problem that the right TF was not always chosen in the TF view
from the list of TFs in a certain motif cluster.

This was due a problem in a custom Comparable method, which was not comparing float
objects correctly. Reversing the order of the 2 float objects to compare, gave the
same result when both float objects where equal to NaN.

This fix also solves the following crash when running iRegulon with Java 7:

    java.lang.IllegalArgumentException: Comparison method violates its general contract!
        at java.util.ComparableTimSort.mergeHi(ComparableTimSort.java:835)
        at java.util.ComparableTimSort.mergeAt(ComparableTimSort.java:453)
        at java.util.ComparableTimSort.mergeForceCollapse(ComparableTimSort.java:392)
        at java.util.ComparableTimSort.sort(ComparableTimSort.java:191)
        at java.util.ComparableTimSort.sort(ComparableTimSort.java:146)
        at java.util.Arrays.sort(Arrays.java:472)
        at java.util.Collections.sort(Collections.java:155)
        at domainmodel.Results.combineTranscriptionFactors(Unknown Source)
        at domainmodel.Results.getMotifAndTrackClusters(Unknown Source)
        at view.resultspanel.motifandtrackclusterview.MotifAndTrackClustersView.refresh(Unknown Source)
        at view.resultspanel.motifandtrackclusterview.MotifAndTrackClustersView.<init>(Unknown Source)
        at view.resultspanel.ResultsCytoPanelComponent.createMainPanel(Unknown Source)
        at view.resultspanel.ResultsCytoPanelComponent.initPanel(Unknown Source)
        at view.resultspanel.ResultsCytoPanelComponent.<init>(Unknown Source)
        at view.actions.PredictRegulatorsAction$1.run(Unknown Source)
        at org.cytoscape.work.internal.task.JDialogTaskManager$TaskRunnable.innerRun(JDialogTaskManager.java:337)
        at org.cytoscape.work.internal.task.JDialogTaskManager$TaskRunnable.run(JDialogTaskManager.java:350)
        at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:471)
        at java.util.concurrent.FutureTask.run(FutureTask.java:262)
        at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1145)
        at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:615)
        at java.lang.Thread.run(Thread.java:745)

In Java 7, the sorting function was changed from "modified mergesort" to "timsort".

JDK-6804124 : (coll) Replace "modified mergesort" in java.util.Arrays.sort with timsort:
    http://bugs.java.com/bugdatabase/view_bug.do?bug_id=6804124

As "timsort" is a stable sort, it did not like the broken custom Comparable method.

Signed-off-by: Gert Hulselmans <gert.hulselmans@med.kuleuven.be>